baseURL = "http://ministry.thestephensons.me.uk/"
languageCode = "en-gb"
title = "Resources for ministry"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  body_classes = "sans-serif"
  post_content_classes = "sans-serif"
  cover_dimming_class = 40
  author = "Tim Stephenson"
  favicon = "favicon.svg"
  site_logo = "/ministry-logo.png"
  description = "Resources for theology, ministry and mission"
  show_reading_time = true
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  recent_posts_number = 6

[[params.ananke_socials]]
#name = "twitter"
#url = "https://twitter.com/GoHugoIO"
