baseURL = "https://ministry.thestephensons.me.uk/"
languageCode = "en-gb"
title = "Resources for Christian ministry"
theme = "ananke"

SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  body_classes = "sans-serif bg-dark-gray"
  post_content_classes = "sans-serif"
  text_color = "near-white"
  secondary_text_color = "light-silver"
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-blue"
  #featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2

[[params.ananke_socials]]
#name = "twitter"
#url = "https://twitter.com/GoHugoIO"
