---
title: "Summary and notes on Augustine's 'Confessions'"
author: Tim Stephenson
date: 2022-02-14T13:30:02Z
summary: A very brief summary of each chapter and highlights of points of personal interest
draft: true
---
:toc:

## Resources

- https://www.stoa.org/hippo/frame_entry.html[Original Latin text and commentary by James O'Donnell]


## Book 1

### Chapter 1

- Can one cry to God for help or must one first know Him?

### Chapter 2

- How can God come to me when a) I am unworthy a place for him to come and b) He is already everywhere?

### Chapter 3

- Is heaven and earth large enough to hold God or does He overflow somewhere else? And anyway heaven and earth is not like a cup holding God but rather the other way around!

- Are certain bits of God in certain places and other bits in other places?

### Chapter 4

- Paradoxes: active, yet resting; gather all, yet needing nothing.

### Chapter 5

- Beseeching God to call and correct.

### Chapter 6

- Every need provided by God from his mother's milk onwards.
- But where was I before my mother's womb, no one can tell me.

> [Should I just] acknowledge you and praise you for what I do know?

- Our 'today' is insignificant compared to your timelessness.

### Chapter 7

The sins of even a one day old baby.

> if babies are innocent, it is not for
lack of will to do harm, but for lack of strength.

### Chapter 8

Learning to speak

> I taught myself by using the intelligence which
you, my God, gave to me.

### Chapter 9

TODO

## BOOK 2

### Chapter 1

Frank and regretful reminiscence of a wild youth.

### Chapter 2

- Confusion of lust with love. An awareness that God was silent, not intervening.
- A view of marriage as a means to tame sin, though not an especially positive view of marriage.
- An awareness of God, in retrospect though not at the time:

> For your almighty power is not far from us, even when we are far from you.

- Harsh words for his family:

> [My family's] only concern was that I should learn how to make a good speech and how to persuade others by my words.

### Chapter 3

- Studies interrupted as he returns home from Madaura, whilst his father seeks to raise money for him to be educated in Carthage. But not out of any concern for his growth in righteousness.
- His mother, though, thought otherwise and was 'apprehensive' and spoke to him [Augustine] as a 'faithful servant'.
- He recognises God's voice in his mother's words in retrospect but at the time revelled not only in 'dissolution' but in the resulting 'applause' of his friends.
- A graphic picture of both parents wishing worldly success above closeness to God.

### Chapter 4

The story of the pear tree and the sin of covetousness, and theft, not for the pears but for the joy of the sin itself.

### Chapter 5

Appreciation of beauty and material goods, but appreciation too of their potential to distract from 'higher goods'.

### Chapter 6

Comparisons of the 'merits' of sins and how they pale compared to God, for example:

> Sloth poses as the love of peace: yet what certain peace is there besides the Lord?

### Chapter 7

- Consciousness of forgiveness and God as forgiver for both sins committed and averted.
- [The first?] recognition of others likewise saved.

### Chapter 8

The companionship of partners in crime also part of the thrill of sin.

### Chapter 9

Confusion that he would not have done the crime alone but:

> ashamed to hold back when others say ‘Come on! Let's do it!'

### Chapter 10

In summary, regret.

## Book 3

### Chapter 11

Seeing Augustine is 'dead by that faith and spirit' she had received, she mournes with 'tears that watered the earth ... in every place she prayed'. In a dream Augustine's mother is told 'that where she was, there I was also', namely in a state of grace. And she relates this to him.

### Chapter 12

His mother implores a bishop to speak to Augustine but he wisely refuses saying he was still too in love with the heresy but urging Monica to pray for her son and he would see his error in due course.

## Book 4

### Chapter 1

From 19-28 he lived as a Manichae, but now confesses the folly in what he was once proud of.

### Chapter 2

Teacher, lover and father.

But would not support a soothsayer to offer sacrifices to devils for their support in a 'theatrical prize'.

### Chapter 3

Turns instead to 'imposters, whom they designate Mathematicians' [astrologers] as they use no sacrifices in their divinations => more acceptable to 'Christian and try piety'.

'A wise man skilled in medicine' tells A that he abandoned astrology, where he had sought a living as he discovered it 'uterly false... and would not gain a living by beguiling people'

Any right predictions are 'pure chance' comparing it to poetry that might seem 'wondrously apposite' though the author intended something far removed.

Yet neither this medic nor 'my most dear Nebridius' could 'persuade me to forsake it'.

### Chapter 4

A friend that he had grown up with and disuaded from Christianity to Manichaeism lies on what all believe is his death bed when he was baptised without his knowledge.

Augustine's comment betrays his firm dualism:

> myself meanwhile little caring, presuming that his soul would retain rather what it had imbibed from me, than what was done to his unconscious body.

https://ereader.perlego.com/1/book/1071715/2?element_plgo_uid=ch2__722&utm_medium=share&utm_campaign=share-with-location&utm_source=perlego[Confessions, Book 4, Chapter 4]

Yet his friend, reviving and learning of the surreptitious baptism did not find Augustine's teasing funny and admonished him. Augustine was 'confounded and confused' but kept quiet thinking to revisit the subject when his friend was fully better. However, before this could happen the fever returned and he died.

Augustine mourns his friend yet does not understand why - to the extent that he writes his tears succeeded his friend as dearest in his affections.

### Chapter 5

Contemplating the sweetness of sorrow, Augustine asks 'is it the hope that Thou hearest us that sweetens it'.

### Chapter 6

How can he continue 'for I felt my soul and his soul were but one soul in two bodies'.

### Chapter 7

Unable to distract himself in any kind of pleasures he flees Thagaste for Carthage once more.

### Chapter 8

Time and friends salve his grief.

### Chapter 9

Love for a person must always die, but loving God can b=never be lost.

### Chapter 10

> Restore us, O Lord God of hosts;
let your face shine, that we may be saved.

https://www.bible.com/en-GB/bible/2016/PSA.80.NRSV[Psalm 80:19]

### Chapter 11-16

TODO

## Book 5

### Chapter 1

> 'Thou alone art near even to those that remove far from Thee.'

> 'Thou wert before me, but I had gone away even from myself; nor did I find myself, much less Thee!'

### Chapter 2

Now 29, Augustine meets Faustus, most eminent Bishop of the Manichaens. He commends the rhetoric, of which he has already heard, but is not taken in by it.

### Chapter 7

It becomes clear that even Faustus cannot untangle all the astronomy of which Mani wrote, and whilst he compliments Faustus on recognising 'he was not altogether ignorant of his own ignorance' and consequently unwilling to be drawn into those things, it is the beginning of the end for Augustine's Manichaenism.

Augustine gives God the glory for thus losening his snare, not deserting his soul and recognising his mother's tears as 'a sacrifice offered to Thee for me'.

### Chapter 8

And so to Rome, despite his mother's lament and urging either not to go or to take her too - even tricking her to do so!

Whilst crediting God for guiding him he says his principal motivation was for better and better behaved students, though he was not blind to potential advancement too.

> But Thou, mysteriously counselling and hearing the real purpose of her desire, granted not what she then asked, in order to make me what she was ever asking.

https://ereader.perlego.com/1/book/1071715/3?element_plgo_uid=ch3__31&utm_medium=share&utm_campaign=share-with-location&utm_source=perlego

### Chapter 9

Still believing the Manichaen understanding that the crucifixtion had been non-corporealy God he takes ill with fever and he fears himself close to death.

He credits that God could not despise the prayers of his mother's 'contrite and humble heart'

### Chapter 10

In Rome he 'joined those deluded and deluding "saints"'

> For it still seemed to me “that it was not we that sin, but that I know not what other nature sinned in us.”

https://ereader.perlego.com/1/book/1071715/3?element_plgo_uid=ch3__134&utm_medium=share&utm_campaign=share-with-location&utm_source=perlego

No longer hopeful to make sense out of what he now regards as a false doctrine, Augustine nontheless continues with it loosely 'for want of something better'.

### Chapter 11

Helpidius - of whom Augustine was aware even in Carthage - disputing with the Manichaens puts arguments he finds persuasive.

### Chapter 12

Fraud by his students, joining other masters to avoid paying fees.

### Chapter 13

Milan seeks a teacher of rhetoric and the then prefect - Symmachus - sends Augustine. Thus he meets Bishop Ambrose 'known to the whole world as among the best of men, Thye devout servant'

> To him was I unknowingly led by Thee, that by him I might knowingly be led to Thee.

https://ereader.perlego.com/1/book/1071715/3?element_plgo_uid=ch3__273&utm_medium=share&utm_campaign=share-with-location&utm_source=perlego

### Chapter 14

So, then, after the manner of the Academics (as they are supposed),5 doubting of everything and fluctuating between all, I decided that the Manichæans were to be abandoned; judging that, even while in that period of doubt, I could not remain in a sect to which I preferred some of the philosophers; to which philosophers, however, because they were without the saving name of Christ, I utterly refused to commit the cure of my fainting soul. I resolved, therefore, to be a catechumen6 in the Catholic Church, which my parents had commended to me, until something settled should manifest itself to me whither I might steer my course.7

## BOOK 6

### Chapter 1

His mother follows Augustine to Milan. An interesting detail that she reassures the sailors of their safe arrival rather than the other way around because of a vision from God.

Augustine tells her he is no longer Manichaen but not yet Catholic and far from being surprised she deeclares '"She believed in Christ, that before she departed this life, she would see me a Catholic believer"'

### Chapter 2

Mother drops her African custom of 'oratories' to the martyrs unquestioningly in light of Ambrose's prohibition

### Chapter 3

Ambrose is busy so Augustine cannot ask his questions about the relative roles of spiritual and physical substance.

### Chapter 4

Augustine resolves his anxiety about the compatibility of infinite Spirit and human Christ

>  In this manner was I confounded and converted, and I rejoiced, O my God, that the one Church, the body of Thine only Son ... did not [have] any tenet that would confine Thee, the Creator of all, in space—though ever so great and wide, yet bounded on all sides by the restraints of a human form.

footnote:[https://ereader.perlego.com/1/book/1071715/3?element_plgo_uid=ch3__499&utm_medium=share&utm_campaign=share-with-location&utm_source=perlego[Confessions Book 6, Chapter 4]]

He commits to memory the rule of Ambrose, frequently expressed, that 'The letter killeth but the Spirit giveth life'.

Though finding nothing offensive in Ambrose's teaching he restrained himself from committing to Catholacism as one who 'has tried a bad physician fears to trust himself to a good one'.
footnote:[https://ereader.perlego.com/1/book/1071715/3?element_plgo_uid=ch3__512&utm_medium=share&utm_campaign=share-with-location&utm_source=perlego[Confessions Book 6, Chapter 4]]

### Chapter 5

Catholocism appears more moderate in its demands of faith than Manichaeism 'that where our credibility was mocked by audacious promise of knowledge ... not capable of demonstration.'

### Chapter 6-12

Friendship and faith of Alypius

### Chapter 13

Mother advises marriage, a girl two years too young for marriage is found and he will wait.

### Chapter 14

Proposal for common retreat from the world of 10 men founders on the question of whether wives actual or potential would tolerate - they would not.

### Chapter 15

His mistress is sent away as an impediment to marriage leaving him with his son, whom he is not capable of coping with so takes a new mistress 'as a slave to lust'.

### Chapter 16

Fear of death and judgement

## Book 7

### Chapter 1

The end of youth (i.e. his thirty-first year!) and transition to 'early manhood'.

Reflecting back?

His vanity in seeking to reconcile God who he believes '_incorruptible, inviolable and unchanging_' with his corruptible, violable and changing experience of the all that is physical.

Rather perceives God as all-pervading spirit.

### Chapter 2

Severe criticism ('_wholly merited to be vomited forth... for speaking such things of thee_') of the Manicheans for their proposal of a negative dark force in opposition to God.

### Chapter 3

'_free will was the cause of our doing evil, and Thy righteous judgement of our suffering it_'.

And yet God, who is '_not only good but goodness itself_', made us, where did the will to do evil come from?

Augustine remains confused.

### Chapter 4

Any substance that is corruptible cannot be God. By definition.

### Chapter 5

'_Whence, therefore, is [evil], seeing that God, who is good, hath made all these things good?_'

Still confused.

### Chapter 6

Augustine is giving up on astrology and quoting Vindicianus and Nebridius that no means of telling the future exists except luck.

An example, by way of proof, of wealthy and slave born at the exact same moment and therefore under the same constellation yet the former rose high and the latter remained low.

Augustine sees similar arguments against astrologers in the lives of twins and of Jacob and Esau.

### Chapter 7

Still asking '_Whence is evil?_' but seeing in his continued faith, preserved by God, evidence for His existence.

Troubled as well as confused.

### Chapter 8

Consolation and healing by '_the secret hand of Thy remedy_'.

### Chapter 9

'_And [the books of the Platonists] I read, not indeed in the same words, but to the selfsame effect, enforced by many and divers reasons, [the arguments of John 1 regarding the Logos]_'

And other comparisons (inclusions and exclusions) of Platonists to Scripture. And concludes that Platonism is inferior because it ends up in foolishness and idolotry.

### Chapter 10

Duly warned of the idolotry, Augustine withdraws into his 'inward self', where he perceives God to lead him on to a clear understanding of Truth, without doubt.

### Chapter 11

Only God is immutable so '_it is good, then, for me to cleave to God_'.

### Chapter 12

All things made by God are good, though not supremely good as they would then be uncorruptible. But evil can have no substance because if it did it would be good [in other words evil is corruption of good things not a thing itself].

### Chapter 13

Evil described as the things that do not harmonize with others. And yet even if that wereall we had of creation we should praise God for creating it.

### Chapter 14

Repenting of his earlier dualist thinking that he entered into because he was 'displeased with' parts of God's creation.

### Chapter 15

Whatever is, is of God and in God.

### Chapter 16

> [evil was not] a substance, but a perversion of the will, bent aside from Thee, O God, The Supreme Substance
footnote:[https://ereader.perlego.com/1/book/1071715/4?element_plgo_uid=ch4__102&utm_medium=share&utm_campaign=share-with-location&utm_source=perlego[Confessions, Book 7, Chapter 16]]

### Chapter 17

He begins to perceive God 'The Unchangeable' above and beyond his own changeable mind.

### Chapter 18

Trying to find the strength to reach God he realises (in the present, but not at that time) that the actual route is through becoming weak and in that weariness to cast himself on Christ through whose mediation he may be lifted up.

### Chapter 19

At that time he did not understand John's phrase 'the word was made flesh' seeing Jesus only as `a man of excellent wisdom`. footnote:[https://ereader.perlego.com/1/book/1071715/4?element_plgo_uid=ch4__223&utm_medium=share&utm_campaign=share-with-location&utm_source=perlego[Confessions, Book 7, Chapter 19]]

### Chapter 20

Glad to have read the Plato before Scriptures in case Plato either undermined his faith or allowed him to think he might have achieved it through Plato alone (which, this way around, he realised could not be the case).

### Chapter 21

Now he is able to appreciate the Scriptures and to grasp that Paul did not contradict himself or the Law and the Prophets as he had thought previously. And he found many wonderful encouragements as well that were not in Plato.

## BOOK 8

Finally, in his 32nd year he is converted.

### Chapter 1


